### ISSUE TITLE
Is the quality option working?

### ISSUE THREAD

**Issue by Retch** [LuisPerisVidal/compress-epub#1] opened 2024-04-16 15:21 UTC
I tried this package and it works very good, but the quality option does not seem to affect the ouput file size, no difference whether 1 or 10.

**Comment by LuisPerisVidal** [comment] 2024-04-16 15:24
Hi @Retch, oohhh you right! My apologies!

In the next 12 hours I'll upload a new version! Thanks for the comment!

**Comment by LuisPerisVidal** [comment] 2024-04-17 06:56
The problem is resolved in the new version 1.10. Thanks for your help :-)

**Closed as completed by LuisPerisVidal** 2024-04-17 06:56 UTC
